### PR TITLE
solved minor bugs: runtime errors for surf and orb Features detector,…

### PR DESCRIPTION
**Pull request by xavkor**
… compilation errors for opencv 2.4.9 with cuda

### CODE REVIEW

**Comment by ahundt** [comment]
There also seems to be a few minor fixes that need to be added to merge after my own recently pushed fixes to the OpenCV3 + non-cuda case.

**Comment by xavkor** [comment]
I made an update to make it works with opencv (2.4.9 and 2.4.11) without cuda.
